name: Generate Hotspots Map

on:
  schedule:
    - cron: '32 04 * * *' # 4:32 AM UTC
    - cron: '33 19 * * *' # 3:30 AM SGT (7:30 PM UTC)
    - cron: '27 07 * * *'  # 3:30 PM SGT (7:30 AM UTC)
  workflow_dispatch:      # Manual trigger button

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate_map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install Python dependencies
        run: pip install boto3 xarray netcdf4 h5netcdf folium matplotlib requests

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

  deploy_pages:
    needs: generate_map
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
